(ql:quickload :cl-fsnotify)

(use-package '#:cl-fsnotify)

(defun run-test ()
  (ensure-directories-exist (pathname "/tmp/owned/"))
  (with-open-file (out-file-three "/tmp/owned/blah3" :direction :output :if-exists :supersede :if-does-not-exist :create)
    (format out-file-three "stuff~%")
    (finish-output out-file-three))
  (open-fsnotify)
  (add-watch "/tmp/owned/")
  (with-open-file (out-file-one "/tmp/owned/blah1" :direction :output :if-exists :append :if-does-not-exist :create)
    (format out-file-one "stuff~%")
    (finish-output out-file-one))
  (format t "~{~A~%~}" (get-events))
  (with-open-file (out-file-two "/tmp/owned/blah2" :direction :output :if-exists :supersede :if-does-not-exist :create)
    (format out-file-two "stuff2~%")
    (finish-output out-file-two))
  (format t "~{~A~%~}" (get-events))
  (delete-file (pathname "/tmp/owned/blah3"))
  (format t "~{~A~%~}" (get-events))
  (format t "~{~A~%~}" (get-events))
  (close-fsnotify))
